# Generated by Django 3.2.11 on 2022-01-31 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('house_no', models.CharField(max_length=255)),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('username', models.CharField(max_length=255)),
                ('national_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=135)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rent', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('block_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.block')),
            ],
        ),
    ]
