# Generated by Django 3.2.11 on 2022-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('house_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('username', models.CharField(max_length=255)),
                ('national_id', models.IntegerField()),
            ],
        ),
    ]
