# Generated by Django 3.2.11 on 2022-01-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='house_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house'),
        ),
    ]
