# Generated by Django 3.2.11 on 2022-02-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payment_house_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myappuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myappuser',
            name='block_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='house_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
    ]
