# Generated by Django 3.2.11 on 2022-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220204_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='house_no',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
